version: "3.2"
services:
  mqtt:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - ./config:/mosquitto/config
      - /project-moyer/docker_volumes/mosquitto/data:/mosquitto/data
      - /project-moyer/docker_volumes/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    restart: unless-stopped
